---
- name: Deploy project
  hosts: all:!localhost
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Deploy from git
      remote_user: riku
      action: >
        git
        repo="{{ repository_url }}"
        dest="{{ project_path }}"
        accept_hostkey=True

    - name: Setup environment config
      remote_user: riku
      template: >
        src=templates/env.j2
        dest="{{ project_path }}/.env"
        mode=775

    - name: Install composer dependencies
      remote_user: riku
      command: composer install chdir="{{ project_path }}"

    - name: Run migrations
      remote_user: riku
      command: php artisan migrate --force chdir="{{ project_path }}"

    - name: Install NVM
      remote_user: riku
      action: >
        git
        repo="https://github.com/creationix/nvm"
        dest="{{ nvm_path }}"

    - name: Make sure Node.js is installed and properly aliased
      remote_user: riku
      command: >
        bash -c "source {{ nvm_script }} && nvm install {{ node_version }} && nvm alias {{ project_name }} {{ node_version }}"
      register: nvm_result
      changed_when: >
        "already installed" not in nvm_result.stdout

    - name: Install client NPM dependencies and build assets
      remote_user: riku
      command: >
        bash -c "source {{ nvm_script }} && nvm use {{ project_name }} && cd {{ project_path }} && npm install && NODE_ENV=production npm run build"
